### PR TITLE
Fix escaping pipe symbol

### LINKED ISSUE #201: Matching Pipe Character, special meaning characters in input text to be escaped
When I paste in:
`|   |   |       13024a.htm`
to generates a regex for it, it uses the pipe as a plain character, which is an alternate selector, so it should be escaped in the regex rather.

### PR DESCRIPTION
**Pull request by noxone**
## Pull request checklist

Please check if your PR fulfills the following requirements:
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Readme.md has been updated to reflect changes.
- [x] Build (`./gradlew build`) was run locally and any changes were pushed

## Pull request type

 

Please check the type of change your PR introduces:
- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

Pipe symbol has not been escaped properly

Closes #201 

## What is the new behavior?

- Pipe symbol is now properly escaped.

### CODE REVIEW

File: src/main/kotlin/org/olafneumann/regex/generator/regex/PatternHelper.kt [hunk 1]
```diff
@@ -1,5 +1,3 @@
 package org.olafneumann.regex.generator.regex
 
-//object PatternHelper {
-fun String.escapeForRegex() = this.replace(RegexCache.get("([.\\\\^$\\[{}()*?+])"), "\\\\$1")
-//}
+fun String.escapeForRegex() = this.replace(RegexCache.get("([|.\\\\^$\\[{}()*?+])"), "\\\\$1")
```
Comment (noxone) [inline src/main/kotlin/org/olafneumann/regex/generator/regex/PatternHelper.kt:3]: Hint for review: I added the pipe symbol in this regex (in the RegexCache#get call)

**Review by lars-sh — COMMENTED** [review]
Seems to be fine.
